# ---------- STAGE 1: Build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files first for better caching
COPY package.json pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm@latest-10
RUN pnpm install

# Copy source code
COPY . .

EXPOSE 3005

# Build the application
ENTRYPOINT [ "pnpm", "run", "dev" ]

# ENTRYPOINT [ "tail", "-f" ]
