// vite.config.ts
import { defineConfig } from 'vite';

export default defineConfig({
  root: './src',  // Where index.html lives
  build: {
    outDir: './build',  // output folder, NOT needed in dev
    emptyOutDir: true,
  },
  server: {
    watch: {
      // 👇 Make Vite watch JS files generated by tsc
      ignored: ['!**/dist/**']
    }
  }
});
